port=53
no-hosts
log-queries
log-facility=/tmp/dnsmasq_primary.log

domain-needed
bogus-priv

server=8.8.8.8
server=1.1.1.1

# Short TTL (30s) for Phase 2 TTL & Migration testing (Extension B)
local-ttl=30

# Domain mapping for Team 1 (Points to Mac 2 Edge Proxy IP)
address=/app.team1.test/10.7.23.158
address=/api.team1.test/10.7.23.158
address=/team1.test/10.7.23.158
